service: ${self:custom.region-name.${self:custom.stage}}PRUEBARIMAC

custom: ${file(customConfig.yml)} 

plugins:
 - serverless-plugin-include-dependencies
 - serverless-offline


provider:
  name: aws
  apiGateway:
    restApiId: i95m2k8tma
    restApiRootResourceId: muooor
  runtime : nodejs10.x
  region: ${self:custom.region.${self:custom.stage}}
  stage: ${opt:stage}
  tracing: true
  timeout: 60
  memorySize: 512
  versionFunctions: false
  stackTags:
    NAME: "Proyecto Prueba"
    ENTORNO: ${self:custom.environments.${self:custom.stage}}
    PROYECTO: ${self:custom.project}
    DOMINIO: ${self:custom.domain}
    RESPONSABLE: ${self:custom.responsable}
    ESTADO_OPERACION: ${self:custom.status}
    MODULO: ${self:custom.module}



package:
  individually: true
  exclude:
    - node_modules/**
    - LMBPRUEBARIMAC/**
    - ./**.json
    - ./**.yml
    - npm-cache/**
    - ./**.sh
functions:
  - ${file(LMBPRUEBARIMAC/lambda_definition.yml)} #LMBPRUEBARIMAC
